"""Initial schema

Revision ID: 74e1785c0a4b
Revises: 
Create Date: 2025-12-01 11:22:58.633245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74e1785c0a4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bertopic_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('time_window_days', sa.Integer(), nullable=False),
    sa.Column('domains_included', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topic_hierarchy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topics_over_time', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visualizations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bertopic_analysis_analysis_date'), 'bertopic_analysis', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_bertopic_analysis_created_at'), 'bertopic_analysis', ['created_at'], unique=False)
    op.create_table('crawl_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('cached_content', sa.Text(), nullable=False),
    sa.Column('cached_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cache_hit_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_crawl_cache_content_hash'), 'crawl_cache', ['content_hash'], unique=False)
    op.create_index(op.f('ix_crawl_cache_domain'), 'crawl_cache', ['domain'], unique=False)
    op.create_index(op.f('ix_crawl_cache_expires_at'), 'crawl_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_crawl_cache_url_hash'), 'crawl_cache', ['url_hash'], unique=False)
    op.create_table('editorial_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('trend_type', sa.String(length=50), nullable=False),
    sa.Column('trend_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_window_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_trends_analysis_date'), 'editorial_trends', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_editorial_trends_domain'), 'editorial_trends', ['domain'], unique=False)
    op.create_index('ix_editorial_trends_domain_date_type', 'editorial_trends', ['domain', 'analysis_date', 'trend_type'], unique=False)
    op.create_table('scraping_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('scraping_allowed', sa.Boolean(), nullable=False),
    sa.Column('disallowed_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('crawl_delay', sa.Integer(), nullable=True),
    sa.Column('user_agent_required', sa.String(length=255), nullable=True),
    sa.Column('robots_txt_content', sa.Text(), nullable=True),
    sa.Column('cache_expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_fetched', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_permissions_cache_expires_at'), 'scraping_permissions', ['cache_expires_at'], unique=False)
    op.create_index(op.f('ix_scraping_permissions_domain'), 'scraping_permissions', ['domain'], unique=True)
    op.create_table('site_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('analysis_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('language_level', sa.String(length=50), nullable=True),
    sa.Column('editorial_tone', sa.String(length=50), nullable=True),
    sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activity_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pages_analyzed', sa.Integer(), nullable=False),
    sa.Column('llm_models_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_profiles_analysis_date'), 'site_profiles', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_site_profiles_domain'), 'site_profiles', ['domain'], unique=True)
    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('was_success', sa.Boolean(), nullable=True),
    sa.Column('parent_execution_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_execution_id'), 'workflow_executions', ['execution_id'], unique=True)
    op.create_foreign_key('fk_workflow_executions_parent_execution_id', 'workflow_executions', 'workflow_executions', ['parent_execution_id'], ['execution_id'])
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_type'), 'workflow_executions', ['workflow_type'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('step_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.execution_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_execution_id'), 'audit_log', ['execution_id'], unique=False)
    op.create_index('ix_audit_log_execution_timestamp', 'audit_log', ['execution_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('competitor_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qdrant_point_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('scraping_permission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['competitor_articles.id'], ),
    sa.ForeignKeyConstraint(['scraping_permission_id'], ['scraping_permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_competitor_articles_domain'), 'competitor_articles', ['domain'], unique=False)
    op.create_index(op.f('ix_competitor_articles_published_date'), 'competitor_articles', ['published_date'], unique=False)
    op.create_index(op.f('ix_competitor_articles_topic_id'), 'competitor_articles', ['topic_id'], unique=False)
    op.create_index(op.f('ix_competitor_articles_url_hash'), 'competitor_articles', ['url_hash'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('metric_unit', sa.String(length=50), nullable=True),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.execution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_created_at'), 'performance_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_performance_metrics_execution_id'), 'performance_metrics', ['execution_id'], unique=False)
    op.create_index('ix_performance_metrics_execution_type', 'performance_metrics', ['execution_id', 'metric_type'], unique=False)
    op.create_index(op.f('ix_performance_metrics_metric_type'), 'performance_metrics', ['metric_type'], unique=False)
    op.create_table('site_analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_profile_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('analysis_phase', sa.String(length=100), nullable=False),
    sa.Column('phase_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('processing_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.execution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_profile_id'], ['site_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_analysis_results_execution_id'), 'site_analysis_results', ['execution_id'], unique=False)
    op.create_index('ix_site_analysis_results_profile_phase', 'site_analysis_results', ['site_profile_id', 'analysis_phase'], unique=False)
    op.create_index(op.f('ix_site_analysis_results_site_profile_id'), 'site_analysis_results', ['site_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_analysis_results_site_profile_id'), table_name='site_analysis_results')
    op.drop_index('ix_site_analysis_results_profile_phase', table_name='site_analysis_results')
    op.drop_index(op.f('ix_site_analysis_results_execution_id'), table_name='site_analysis_results')
    op.drop_table('site_analysis_results')
    op.drop_index(op.f('ix_performance_metrics_metric_type'), table_name='performance_metrics')
    op.drop_index('ix_performance_metrics_execution_type', table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_execution_id'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_created_at'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_competitor_articles_url_hash'), table_name='competitor_articles')
    op.drop_index(op.f('ix_competitor_articles_topic_id'), table_name='competitor_articles')
    op.drop_index(op.f('ix_competitor_articles_published_date'), table_name='competitor_articles')
    op.drop_index(op.f('ix_competitor_articles_domain'), table_name='competitor_articles')
    op.drop_table('competitor_articles')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index('ix_audit_log_execution_timestamp', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_execution_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_workflow_executions_workflow_type'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_constraint('fk_workflow_executions_parent_execution_id', 'workflow_executions', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_executions_execution_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_site_profiles_domain'), table_name='site_profiles')
    op.drop_index(op.f('ix_site_profiles_analysis_date'), table_name='site_profiles')
    op.drop_table('site_profiles')
    op.drop_index(op.f('ix_scraping_permissions_domain'), table_name='scraping_permissions')
    op.drop_index(op.f('ix_scraping_permissions_cache_expires_at'), table_name='scraping_permissions')
    op.drop_table('scraping_permissions')
    op.drop_index('ix_editorial_trends_domain_date_type', table_name='editorial_trends')
    op.drop_index(op.f('ix_editorial_trends_domain'), table_name='editorial_trends')
    op.drop_index(op.f('ix_editorial_trends_analysis_date'), table_name='editorial_trends')
    op.drop_table('editorial_trends')
    op.drop_index(op.f('ix_crawl_cache_url_hash'), table_name='crawl_cache')
    op.drop_index(op.f('ix_crawl_cache_expires_at'), table_name='crawl_cache')
    op.drop_index(op.f('ix_crawl_cache_domain'), table_name='crawl_cache')
    op.drop_index(op.f('ix_crawl_cache_content_hash'), table_name='crawl_cache')
    op.drop_table('crawl_cache')
    op.drop_index(op.f('ix_bertopic_analysis_created_at'), table_name='bertopic_analysis')
    op.drop_index(op.f('ix_bertopic_analysis_analysis_date'), table_name='bertopic_analysis')
    op.drop_table('bertopic_analysis')
    # ### end Alembic commands ###

